# Generated by Django 3.2.13 on 2022-06-16 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=uuid.UUID('bb787509-1bf0-49fb-a07a-8019ab4e8826'), primary_key=True, serialize=False, unique=True),
        ),
    ]
