# Generated by Django 3.2.13 on 2022-06-19 22:50

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220617_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=0, default_currency='USD', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0'), default_currency='USD', max_digits=14),
        ),
    ]
