# Generated by Django 3.2.13 on 2022-06-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csv',
            options={'permissions': (('can_upload_csv', 'Upload CSV files to database'),)},
        ),
    ]
